### ISSUE TITLE
Molusce tab not highlighted and cannot be used

### ISSUE THREAD

**Issue by Enyboi** [nextgis/qgis_molusce#21]
I have an issue using the molusce plugging on my QGIS 2.18.11. The tabs for evaluating correlation, area changes, transition potential modelling, cellular automata simulation and validation are not highlighted and could not be used. its only inputs and messages tabs that are highlighted on the task bar. Can anyone kindly help me with this? Thank you in advance

**Comment by KolesovDmitry** [comment]
The tabs are 'inactive' initially. You have to 
 (a) open rasters and fill the input strings on the first tab 
 (b) check if geometries of the rasters are matched. 

The tabs will be active after that (in case in the geometries are matched).

**Comment by Enyboi** [comment]
Thank you Dmitry. The geometry of my LULC maps and the spatial variables (roads and slope) do not match. Any idea on what I can do? Thank you

**Comment by simgislab** [comment]
https://github.com/nextgis/molusce/issues/10

**Comment by Enyboi** [comment]
Thank you. problem of geometry match solved but had another problem when trying to create changes map. I will post the error message below:

**Comment by Enyboi** [comment]
This is the error message I got while trying to create changes map. Is there anything I am not doing right?

2017-10-26T23:26:19	1	Traceback (most recent call last):
			  File "C:/Users/OWNER/.qgis2/python/plugins\molusce\moluscedialog.py", line 467, in createChangeMap self.analyst = AreaAnalyst(self.inputs["initial"], self.inputs["final"])
			  FileC:/Users/OWNER/.qgis2/python/plugins\molusce\algorithms\models\area_analysis\manager.py", line 62, in __init__  raise AreaAnalizerError("List of categories of the first raster doesn't contains a category of the second raster!")
			AreaAnalizerError
			
2017-10-26T23:37:37	1	Traceback (most recent call last):
			  File "C:/Users/OWNER/.qgis2/python/plugins\molusce\moluscedialog.py", line 467, in createChangeMap
			    self.analyst = AreaAnalyst(self.inputs["initial"], self.inputs["final"])
			  File "C:/Users/OWNER/.qgis2/python/plugins\molusce\algorithms\models\area_analysis\manager.py", line 62, in __init__
			    raise AreaAnalizerError("List of categories of the first raster doesn't contains a category of the second raster!")
			AreaAnalizerError
			
2017-10-26T23:38:49	1	Traceback (most recent call last):
			  File "C:/Users/OWNER/.qgis2/python/plugins\molusce\moluscedialog.py", line 467, in createChangeMap
			    self.analyst = AreaAnalyst(self.inputs["initial"], self.inputs["final"])
			  File "C:/Users/OWNER/.qgis2/python/plugins\molusce\algorithms\models\area_analysis\manager.py", line 62, in __init__
			    raise AreaAnalizerError("List of categories of the first raster doesn't contains a category of the second raster!")
			AreaAnalizerError
			
2017-10-26T23:49:25	1	Traceback (most recent call last):
			  File "C:/Users/OWNER/.qgis2/python/plugins\molusce\moluscedialog.py", line 467, in createChangeMap
			    self.analyst = AreaAnalyst(self.inputs["initial"], self.inputs["final"])
			  File "C:/Users/OWNER/.qgis2/python/plugins\molusce\algorithms\models\area_analysis\manager.py", line 62, in __init__
			    raise AreaAnalizerError("List of categories of the first raster doesn't contains a category of the second raster!")
			AreaAnalizerError
			
Thank you for your assistance

**Comment by simgislab** [comment]
the error message is self-explanatory, make raster categories match

**Comment by Enyboi** [comment]
Thanks for your response. This is my first time of trying the molusce plugging. In fact, I started using QGIS less than 2 months ago when i discovered it can solve the problem I have been having for long on other GIS software I was using for my thesis. I will attend to it.

**Comment by Enyboi** [comment]
I kindly need help here. I got through all my initial challenges, but anything I got to Cellullar Automata Simulation to simulate the future change. Entered the certainty function and the location of simulation output, push the start tab to begin prediction, molusce and QGIS kept crashing, which has happened three times now. I couldn't read the error message..... because it crashed before the error message can be displayed properly. 

Any help please? I need to submit this work to thesis director by Monday. Thank you

**Comment by KasturiRoy** [comment]
Hi everyone,
I am new to MOLUSCE Plugin, and when I try to create tables, I get this error:

Traceback (most recent call last):
			  File "C:/Users/Kasturi Roy/.qgis2/python/plugins\molusce\moluscedialog.py", line 444, in updateStatisticsTableDone
			    self.__drawTransitionStat()
			  File "C:/Users/Kasturi Roy/.qgis2/python/plugins\molusce\moluscedialog.py", line 1058, in __drawTransitionStat
			    stat = self.inputs["crosstab"].getTransitionStat()
			  File "C:/Users/Kasturi Roy/.qgis2/python/plugins\molusce\algorithms\models\crosstabs\manager.py", line 79, in getTransitionStat
			    initArea = tab.getSumRows()
			  File "C:/Users/Kasturi Roy/.qgis2/python/plugins\molusce\algorithms\models\crosstabs\model.py", line 125, in getSumRows
			    crosstable = self.getCrosstable()
			  File "C:/Users/Kasturi Roy/.qgis2/python/plugins\molusce\algorithms\models\crosstabs\model.py", line 86, in getCrosstable
			    if self._T == None:
			ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

 I am not sure what needs to be done, therefpre, sny help will be highly appreciated.
Thanks in advance!

**Comment by Astori68** [comment]
My Landuse/cover maps and spatial variables geometry do not match. kindly help me how to fix the issue.

**Comment by Shinjita** [comment]
Hi @KasturiRoy i am having the same problem as well? Do you know how to fix this issue??

**Comment by G-0510** [comment]
hello guys, I m using Qgis 2.16 in windows 10. In using Molusce plugin i am facing problem in Validation tab the error shows is:-
MemoryError 
Traceback (most recent call last):
  File "C:/Users/gaurav jaiswal/.qgis2/python/plugins\molusce\moluscedialog.py", line 648, in startValidation
    self.eb = EBudget(reference, simulated)
  File "C:/Users/gaurav jaiswal/.qgis2/python/plugins\molusce\algorithms\models\errorbudget\ebmodel.py", line 90, in __init__
    self.Sj[j] = 1.0*binaryzation(S, [j])
  File "C:\PROGRA~2\QGIS 2.16\apps\Python27\lib\site-packages\numpy\ma\core.py", line 3947, in __rmul__
    return multiply(other, self)
  File "C:\PROGRA~2\QGIS 2.16\apps\Python27\lib\site-packages\numpy\ma\core.py", line 966, in __call__
    result = self.f(da, db, *args, **kwargs)
MemoryError


Python version: 2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)] 
QGIS version: 2.16.3 Nødebo, 7d00cae 

I m not able to proceed further pls help me
Gaurav

**Comment by bzst233** [comment]
> hello guys, I m using Qgis 2.16 in windows 10. In using Molusce plugin i am facing problem in Validation tab the error shows is:- MemoryError Traceback (most recent call last): File "C:/Users/gaurav jaiswal/.qgis2/python/plugins\molusce\moluscedialog.py", line 648, in startValidation self.eb = EBudget(reference, simulated) File "C:/Users/gaurav jaiswal/.qgis2/python/plugins\molusce\algorithms\models\errorbudget\ebmodel.py", line 90, in **init** self.Sj[j] = 1.0*binaryzation(S, [j]) File "C:\PROGRA~2\QGIS 2.16\apps\Python27\lib\site-packages\numpy\ma\core.py", line 3947, in **rmul** return multiply(other, self) File "C:\PROGRA~2\QGIS 2.16\apps\Python27\lib\site-packages\numpy\ma\core.py", line 966, in **call** result = self.f(da, db, *args, **kwargs) MemoryError
> 
> Python version: 2.7.4 (default, Apr 6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)] QGIS version: 2.16.3 Nødebo, 7d00cae
> 
> I m not able to proceed further pls help me Gaurav

I do have the same problem. Have you sloved it?

**Comment by simgislab** [comment]
Try brand new MOLUSCE 4 for QGIS 3 and let us know if the problem persists
