### ISSUE TITLE
TypeError: QgsCollapsibleGroupBox.setSettings(QgsSettings): argument 1 has unexpected type 'QSettings' 

### ISSUE THREAD

**Issue by BahramGITH** [nextgis/qgis_molusce#26]
Hi there!
Anytime that I try to open the **molusce** tool I face this error message!
```
TypeError: QgsCollapsibleGroupBox.setSettings(QgsSettings): argument 1 has unexpected type 'QSettings' 
Traceback (most recent call last):
  File "C:/Users/Jomehzadeh/.qgis2/python/plugins\molusce\molusce.py", line 109, in run
    d = moluscedialog.MolusceDialog(self.iface)
  File "C:/Users/Jomehzadeh/.qgis2/python/plugins\molusce\moluscedialog.py", line 110, in __init__
    self.grpSampling.setSettings(self.settings)
TypeError: QgsCollapsibleGroupBox.setSettings(QgsSettings): argument 1 has unexpected type 'QSettings'
```
**OS version Windows 10
Python version: 2.7.5
QGIS version: 2.18.14 Las Palmas**

I appreciate any help!
Best regards!

**Comment by juda-garcia** [comment]
what you were runing when this shows up?

**Comment by simgislab** [comment]
Try brand new MOLUSCE 4 for QGIS 3 and let us know if the problem persists. Reopen if necessary.
