### ISSUE TITLE
Pyhton Memory Error while running MOLUSCE plugin

### ISSUE THREAD

**Issue by purnendusardar** [nextgis/qgis_molusce#35]
I have been trying to use MOLUSCE plugin. The plugin shows Python Memory error when I tried to train the ANN for Transition Potential Modelling. I saw a suggestion for using appropriate coordinate system for the raster data sets which will use the Earth as a flat surface. So I converted all my raster to same UTM projection. Same problem occurred again at the same step. The error code looks like following:
2019-08-28T11:39:14	1	Traceback (most recent call last):
			  File "C:/Users/GISLab08/.qgis2/python/plugins\molusce\neuralnetworkwidget.py", line 138, in trainNetwork
			    samples=self.plugin.spnSamplesCount.value()
			  File "C:/Users/GISLab08/.qgis2/python/plugins\molusce\algorithms\models\mlp\manager.py", line 341, in setTrainingData
			    f.normalize(mode = 'mean')
			  File "C:/Users/GISLab08/.qgis2/python/plugins\molusce\algorithms\dataprovider.py", line 257, in normalize
			    stat = self.getBandStat(i)
			  File "C:/Users/GISLab08/.qgis2/python/plugins\molusce\algorithms\dataprovider.py", line 163, in getBandStat
			    result['mean'] = np.ma.mean(band)
			  File "C:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\site-packages\numpy\ma\core.py", line 6354, in __call__
			    return method(*args, **params)
			  File "C:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\site-packages\numpy\ma\core.py", line 5065, in mean
			    dsum = self.sum(axis=axis, dtype=dtype)
			  File "C:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\site-packages\numpy\ma\core.py", line 4820, in sum
			    result = self.filled(0).sum(axis, dtype=dtype)
			  File "C:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\site-packages\numpy\ma\core.py", line 3635, in filled
			    result = self._data.copy('K')
			MemoryError

**Comment by simgislab** [comment]
Try brand new MOLUSCE 4 for QGIS 3 and let us know if the problem persists. Reopen if necessary.
