### ISSUE TITLE
Area Changes error

### ISSUE THREAD

**Issue by sultanbolat** [nextgis/qgis_molusce#41]
Hello,
When I use 'molusce' plugin I get the following error in the area changes section and I do not know how to fix this. If you could help me that would be great!

Traceback (most recent call last):
			  File "C:/Users/Sultan/.qgis2/python/plugins\molusce\moluscedialog.py", line 444, in updateStatisticsTableDone
			    self.__drawTransitionStat()
			  File "C:/Users/Sultan/.qgis2/python/plugins\molusce\moluscedialog.py", line 1058, in __drawTransitionStat
			    stat = self.inputs["crosstab"].getTransitionStat()
			  File "C:/Users/Sultan/.qgis2/python/plugins\molusce\algorithms\models\crosstabs\manager.py", line 79, in getTransitionStat
			    initArea = tab.getSumRows()
			  File "C:/Users/Sultan/.qgis2/python/plugins\molusce\algorithms\models\crosstabs\model.py", line 125, in getSumRows
			    crosstable = self.getCrosstable()
			  File "C:/Users/Sultan/.qgis2/python/plugins\molusce\algorithms\models\crosstabs\model.py", line 86, in getCrosstable
			    if self._T == None:
			ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by DawnBrawn** [comment]
I got the same error while creating the Area Changes.

**Comment by salsabeeeel** [comment]
I'm getting the same error, did anyone get the solution for this?

**Comment by esimoes1** [comment]
Please, did anyone get the solution for this?

**Comment by simgislab** [comment]
Try brand new MOLUSCE 4 for QGIS 3 and let us know if the problem persists. Reopen if necessary.
