### ISSUE TITLE
Cannot create change table and change map

### ISSUE THREAD

**Issue by anackr** [nextgis/qgis_molusce#53]
I am using [these rasters](https://drive.google.com/drive/folders/16D6yv9Ws3dFCqthsmHju1Qup2bdmV178?usp=sharing) to make a change map from 1992 to 2007 and validate on 2021. My LULC classes are small numbers (0-6). Geometries are valid and correlations are acceptable. However, when I go to Area Changes the problems come up.
When I click on Update tables (independently of the unit), it loads but no table appears.
When I click on Create changes map, I can open my files and name it, but on the following page it says that no change map was created.
Also, after some time, a window popped up with the following message:

_ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all() 
Traceback (most recent call last):
  File "C:/Users/anacl/.qgis2/python/plugins\molusce\moluscedialog.py", line 444, in updateStatisticsTableDone
    self.__drawTransitionStat()
  File "C:/Users/anacl/.qgis2/python/plugins\molusce\moluscedialog.py", line 1058, in __drawTransitionStat
    stat = self.inputs["crosstab"].getTransitionStat()
  File "C:/Users/anacl/.qgis2/python/plugins\molusce\algorithms\models\crosstabs\manager.py", line 79, in getTransitionStat
    initArea = tab.getSumRows()
  File "C:/Users/anacl/.qgis2/python/plugins\molusce\algorithms\models\crosstabs\model.py", line 125, in getSumRows
    crosstable = self.getCrosstable()
  File "C:/Users/anacl/.qgis2/python/plugins\molusce\algorithms\models\crosstabs\model.py", line 86, in getCrosstable
    if self._T == None:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()_

I am using QGIS 2.18.28.
On QGIS 2.16.3 and 2.14.9 the table appears but when trying to create Change map, the program crashes and closes.

Could anyone help, please?

**Comment by ivanbarsukov** [comment]
This bug is fixed in MOLUSCE 4.0
